image: registry.gitlab.com/mfep/midi-connector

build:
  stage: build
  script:
    - git submodule update --init
    - cd deps/rtmidi
    - cmake -S . -B build -D RTMIDI_BUILD_STATIC_LIBS=ON
    - cmake --build build --config Release --target install
    - mv /usr/local/share/rtmidi/RtMidi-config.cmake /usr/local/share/rtmidi/rtmidi-config.cmake 
    - cd ../..
    - cmake -S . -B build -D CMAKE_CXX_FLAGS="-Wall -Wextra"
    - cmake --build build --config Release
