image: registry.gitlab.com/mfep/midi-connector

default:
  interruptible: true

build-linux:
  stage: build
  script:
    - git submodule update --init
    - cd deps/rtmidi
    - cmake -S . -B build -D RTMIDI_BUILD_STATIC_LIBS=ON
    - cmake --build build --config Release --target install
    - mv /usr/local/share/rtmidi/RtMidi-config.cmake /usr/local/share/rtmidi/rtmidi-config.cmake 
    - cd ../..
    - cmake -S . -B build -D CMAKE_CXX_FLAGS="-Wall -Wextra"
    - cmake --build build --config Release
  artifacts:
    paths:
      - build/midi_connector
    expire_in: 1 week

build-windows:
  stage: build
  tags:
    - shared-windows
    - windows
    - windows-1809
  script:
    - wget.exe https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-x86_64.zip
    - 7z e cmake-3.22.2-windows-x86_64.zip
    - set PATH="%PATH%;cmake-3.22.2-windows-x86_64/bin"
    - git submodule update --init
    - cd deps/rtmidi
    - cmake -S . -B build -D RTMIDI_BUILD_STATIC_LIBS=ON
    - cmake --build build --config Release
    - cd ../..
    - cmake -S . -B build
    - cmake --build build --config Release