image: registry.gitlab.com/mfep/midi-connector

default:
  interruptible: true

build-linux:
  stage: build
  script:
    - git submodule update --init
    - cmake -S . -B build -D CMAKE_CXX_FLAGS="-Wall -Wextra" -D COMMIT_HASH=${CI_COMMIT_SHA}
    - cmake --build build --config Release
  artifacts:
    paths:
      - build/midi_connector
    expire_in: 1 week

build-windows:
  stage: build
  tags:
    - shared-windows
    - windows
    - windows-1809
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - when: manual
      allow_failure: true
  before_script:
    - pwd
    - cd C:/vcpkg
    - git fetch
    - git checkout master
    - git pull
    - bootstrap-vcpkg.bat
  script:
    - cd C:/GitLab-Runner/builds/mfep/midi-connector
    - vcpkg install spdlog:x64-windows sdl2:x64-windows
    - wget.exe https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-x86_64.zip
    - 7z x -y cmake-3.22.2-windows-x86_64.zip
    - git submodule update --init
    - cmake-3.22.2-windows-x86_64/bin/cmake -S . -B build -D CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -D COMMIT_HASH=${CI_COMMIT_SHA}
    - cmake-3.22.2-windows-x86_64/bin/cmake --build build --config Release
  artifacts:
    paths:
      - build/Release/midi_connector.exe
      - build/Release/*.dll
    expire_in: 1 week
