
default:
  interruptible: true

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - release

.rules:optional:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG == null
      when: manual
      allow_failure: true

build-linux:
  image: registry.gitlab.com/mfep/midiconn:latest
  stage: build
  script:
    - cmake -S . -B build
      -D CMAKE_CXX_FLAGS="-Wall -Wextra"
      -D CMAKE_BUILD_TYPE=Release
      -D MC_COMMIT_SHA=${CI_COMMIT_SHA}
      -D MC_BUILD_NUMBER=${CI_JOB_ID}
      -D CPACK_GENERATOR=DEB
    - cmake --build build -j `nproc`
    - cd build
    - cpack -C Release
  artifacts:
    paths:
      - build/midiconn
      - build/*.deb
    expire_in: 1 week

build-linux-flatpak:
  stage: build
  image: ubuntu:22.04
  extends:
    - .rules:optional
  script:
    - apt-get update -y && apt-get install -y flatpak-builder appstream-util
    - appstream-util validate $CI_PROJECT_DIR/packaging/xyz.safeworlds.midiconn.metainfo.xml
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.freedesktop.Sdk//22.08 org.freedesktop.Platform//22.08
    - flatpak-builder build/flatpak $CI_PROJECT_DIR/packaging/xyz.safeworlds.midiconn.yml
  artifacts:
    paths:
      - build/flatpak
    expire_in: 1 week
  cache:
    paths:
      - .flatpak-builder

build-windows:
  stage: build
  extends:
    - .rules:optional
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - cd C:/vcpkg
    - git fetch
    - git checkout master
    - git pull
    - bootstrap-vcpkg.bat
    - vcpkg install spdlog:x64-windows sdl2:x64-windows freetype[core]:x64-windows rtmidi:x64-windows
  script:
    - cd C:/GitLab-Runner/builds/mfep/midiconn
    - wget.exe https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-x86_64.zip
    - 7z x -y cmake-3.22.2-windows-x86_64.zip
    - wget.exe https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
    - 7z x -y wix311-binaries.zip
    - $env:PATH = "$env:PATH;C:/GitLab-Runner/builds/mfep/midiconn"
    - git submodule update --init
    - cmake-3.22.2-windows-x86_64/bin/cmake
      -S .
      -B build
      -D CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake
      -D MC_COMMIT_SHA=${CI_COMMIT_SHA}
      -D MC_CHECK_FOR_UPDATES=ON
    - cmake-3.22.2-windows-x86_64/bin/cmake --build build --config Release
    - cd C:/GitLab-Runner/builds/mfep/midiconn/build
    - ../cmake-3.22.2-windows-x86_64/bin/cpack -C Release
  artifacts:
    paths:
      - build/Release/*.exe
      - build/Release/*.dll
      - build/*.msi
    expire_in: 1 week

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build-linux
    - build-windows
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Running release"
  artifacts:
    paths:
      - build/midiconn-${CI_COMMIT_TAG}-win64.msi
      - build/midiconn-${CI_COMMIT_TAG}-Linux.deb
    expire_in: never
  release:
    tag_name: $CI_COMMIT_TAG
    name: Release $CI_COMMIT_TAG
    description: $CI_COMMIT_TAG_MESSAGE
    assets:
      links:
        - name: Linux DEB package (Ubuntu 22.04)
          url: ${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/build/midiconn-${CI_COMMIT_TAG}-Linux.deb
        - name: Windows MSI installer
          url: ${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/raw/build/midiconn-${CI_COMMIT_TAG}-win64.msi

release-itch:
  stage: release
  image: ubuntu:22.04
  needs:
    - release-job
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - apt update -y
    - apt install -y wget unzip
  script:
    - wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -O butler.zip
    - unzip butler.zip
    - ./butler push ${CI_PROJECT_DIR}/build/midiconn-${CI_COMMIT_TAG}-win64.msi mfeproject/midiconn:windows-msi --userversion ${CI_COMMIT_TAG}
    - ./butler push ${CI_PROJECT_DIR}/build/midiconn-${CI_COMMIT_TAG}-Linux.deb mfeproject/midiconn:ubuntu2204-deb --userversion ${CI_COMMIT_TAG}
