
default:
  interruptible: true

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.rules:optional:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: manual
      allow_failure: true

build-linux:
  image: registry.gitlab.com/mfep/midiconn:latest
  stage: build
  script:
    - cmake -S . -B build
      -D CMAKE_CXX_FLAGS="-Wall -Wextra"
      -D CMAKE_BUILD_TYPE=Release
      -D MC_COMMIT_SHA=${CI_COMMIT_SHA}
      -D MC_BUILD_NUMBER=${CI_JOB_ID}
    - cmake --build build -j `nproc`
  artifacts:
    paths:
      - build/midiconn
    expire_in: 1 week

build-linux-flatpak:
  stage: build
  image: ubuntu
  extends:
    - .rules:optional
  script:
    - apt-get update -y && apt-get install -y flatpak-builder
    - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - flatpak install -y flathub org.freedesktop.Sdk//21.08 org.freedesktop.Platform//21.08
    - flatpak-builder build/flatpak packaging/midiconn.yml
  artifacts:
    paths:
      - build/flatpak
    expire_in: 1 week
  cache:
    paths:
      - .flatpak-builder

build-windows:
  stage: build
  extends:
    - .rules:optional
  tags:
    - shared-windows
    - windows
    - windows-1809
  before_script:
    - cd C:/vcpkg
    - git fetch
    - git checkout master
    - git pull
    - bootstrap-vcpkg.bat
    - vcpkg install spdlog:x64-windows sdl2:x64-windows freetype[core]:x64-windows rtmidi:x64-windows
  script:
    - cd C:/GitLab-Runner/builds/mfep/midiconn
    - wget.exe https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-windows-x86_64.zip
    - 7z x -y cmake-3.22.2-windows-x86_64.zip
    - wget.exe https://github.com/wixtoolset/wix3/releases/download/wix3112rtm/wix311-binaries.zip
    - 7z x -y wix311-binaries.zip
    - $env:PATH = "$env:PATH;C:/GitLab-Runner/builds/mfep/midiconn"
    - git submodule update --init
    - cmake-3.22.2-windows-x86_64/bin/cmake -S . -B build -D CMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -D MC_COMMIT_SHA=${CI_COMMIT_SHA}
    - cmake-3.22.2-windows-x86_64/bin/cmake --build build --config Release
    - cd C:/GitLab-Runner/builds/mfep/midiconn/build
    - ../cmake-3.22.2-windows-x86_64/bin/cpack -C Release
  artifacts:
    paths:
      - build/Release/*.exe
      - build/Release/*.dll
      - build/*.msi
    expire_in: 1 week
