from_latest_tag = true
ignore_merge_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "grep version=\\\"{{latest}}\\\" data/packaging/xyz.safeworlds.midiconn.metainfo.xml",
    "sed -i \"s|project(midiconn VERSION [0-9]\\+.[0-9]\\+.[0-9]\\+|project(midiconn VERSION {{version}}|\" CMakeLists.txt"
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []
tag_prefix = "v"

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "midiconn"
owner = "mfep"
template = "remote"
authors = [
    { signature = "Lőrinc Serfőző", username = "mfep" }
]

[bump_profiles]

[packages]
