#include "Licenses.hpp"

namespace mc
{

std::vector<License> g_licenses{
    {"SDL 2.0",
     "This software is provided 'as-is', without any express or implied\n"
     "warranty.  In no event will the authors be held liable for any damages\n"
     "arising from the use of this software.\n"
     "\n"
     "Permission is granted to anyone to use this software for any purpose,\n"
     "including commercial applications, and to alter it and redistribute it\n"
     "freely, subject to the following restrictions:\n"
     "\n"
     "1. The origin of this software must not be misrepresented; you must not\n"
     "   claim that you wrote the original software. If you use this software\n"
     "   in a product, an acknowledgment in the product documentation would be\n"
     "   appreciated but is not required.\n"
     "2. Altered source versions must be plainly marked as such, and must not be\n"
     "   misrepresented as being the original software.\n"
     "3. This notice may not be removed or altered from any source distribution.\n"},
    {"RtMidi: realtime MIDI i/o C++ classes",
     "Copyright (c) 2003-2021 Gary P. Scavone\n"
     "\n"
     "Permission is hereby granted, free of charge, to any person\n"
     "obtaining a copy of this software and associated documentation files\n"
     "(the \"Software\"), to deal in the Software without restriction,\n"
     "including without limitation the rights to use, copy, modify, merge,\n"
     "publish, distribute, sublicense, and/or sell copies of the Software,\n"
     "and to permit persons to whom the Software is furnished to do so,\n"
     "subject to the following conditions:\n"
     "\n"
     "The above copyright notice and this permission notice shall be\n"
     "included in all copies or substantial portions of the Software.\n"
     "\n"
     "Any person wishing to distribute modifications to the Software is\n"
     "asked to send the modifications to the original developer so that\n"
     "they can be incorporated into the canonical version.  This is,\n"
     "however, not a binding provision of this license.\n"
     "\n"
     "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n"
     "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n"
     "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n"
     "IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR\n"
     "ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF\n"
     "CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION\n"
     "WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"           },
    {"Dear ImGui",
     "The MIT License (MIT)\n"
     "\n"
     "Copyright (c) 2014-2022 Omar Cornut\n"
     "\n"
     "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
     "of this software and associated documentation files (the \"Software\"), to deal\n"
     "in the Software without restriction, including without limitation the rights\n"
     "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
     "copies of the Software, and to permit persons to whom the Software is\n"
     "furnished to do so, subject to the following conditions:\n"
     "\n"
     "The above copyright notice and this permission notice shall be included in all\n"
     "copies or substantial portions of the Software.\n"
     "\n"
     "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
     "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
     "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
     "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
     "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
     "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
     "SOFTWARE.\n"                                                                 },
    {"imnodes",
     "The MIT License (MIT)\n"
     "\n"
     "Copyright (c) 2019 Johann Muszynski\n"
     "\n"
     "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
     "of this software and associated documentation files (the \"Software\"), to deal\n"
     "in the Software without restriction, including without limitation the rights\n"
     "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
     "copies of the Software, and to permit persons to whom the Software is\n"
     "furnished to do so, subject to the following conditions:\n"
     "\n"
     "The above copyright notice and this permission notice shall be included in all\n"
     "copies or substantial portions of the Software.\n"
     "\n"
     "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
     "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
     "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
     "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
     "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
     "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
     "SOFTWARE.\n"                                                                 },
    {"spdlog",
     "The MIT License (MIT)\n"
     "\n"
     "Copyright (c) 2016 Gabi Melman.                                       \n"
     "\n"
     "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
     "of this software and associated documentation files (the \"Software\"), to deal\n"
     "in the Software without restriction, including without limitation the rights\n"
     "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
     "copies of the Software, and to permit persons to whom the Software is\n"
     "furnished to do so, subject to the following conditions:\n"
     "\n"
     "The above copyright notice and this permission notice shall be included in\n"
     "all copies or substantial portions of the Software.\n"
     "\n"
     "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
     "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
     "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE\n"
     "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
     "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
     "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
     "THE SOFTWARE.\n"
     "\n"
     "-- NOTE: Third party dependency used by this software --\n"
     "This software depends on the fmt lib (MIT License),\n"
     "and users must comply to its license: "
     "https://github.com/fmtlib/fmt/blob/master/LICENSE.rst\n"                     },
    {"nlohmann/json",
     "MIT License \n"
     "\n"
     "Copyright (c) 2013-2022 Niels Lohmann\n"
     "\n"
     "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
     "of this software and associated documentation files (the \"Software\"), to deal\n"
     "in the Software without restriction, including without limitation the rights\n"
     "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
     "copies of the Software, and to permit persons to whom the Software is\n"
     "furnished to do so, subject to the following conditions:\n"
     "\n"
     "The above copyright notice and this permission notice shall be included in all\n"
     "copies or substantial portions of the Software.\n"
     "\n"
     "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
     "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
     "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
     "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
     "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
     "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
     "SOFTWARE.\n"                                                                 },
    {"Portable File Dialogs",
     "            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n"
     "                    Version 2, December 2004\n"
     "\n"
     " Copyright (C) 2004 Sam Hocevar\n"
     "\n"
     " Everyone is permitted to copy and distribute verbatim or modified\n"
     " copies of this license document, and changing it is allowed as long\n"
     " as the name is changed.\n"
     "\n"
     "            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE\n"
     "   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n"
     "\n"
     "  0. You just DO WHAT THE FUCK YOU WANT TO.\n"
     "\n"                                                                          }
};

}
