function (EmbedBinaryFile file_path variable_name generated_file_path_out)
    message(STATUS "Generating embedded binary for ${file_path}")
    file(READ ${file_path} file_content HEX)
    string(REGEX MATCHALL "([A-Fa-f0-9][A-Fa-f0-9])" separated_content ${file_content})
    foreach(byte IN LISTS separated_content)
        string(APPEND output_string "0x${byte},")
    endforeach()
    get_filename_component(base_filename ${file_path} NAME_WLE)
    set(generated_file_path "${CMAKE_BINARY_DIR}/${base_filename}.cpp")
    file(WRITE ${generated_file_path} "unsigned char ${variable_name}[] = {${output_string}};unsigned long long ${variable_name}_size = sizeof(${variable_name});")
    set(${generated_file_path_out} ${generated_file_path} PARENT_SCOPE)
endfunction()
