name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Install prerequisites
      run: sudo apt-get install -y
        libasound2-dev
        libfmt-dev
        libfreetype-dev
        libsdl2-dev
        libspdlog-dev
        xorg-dev
    - name: Configure CMake
      run: cmake
        -B ${{github.workspace}}/build
        -D CMAKE_CXX_FLAGS="-Wall -Wextra"
        -D CMAKE_BUILD_TYPE=Release
        -D MC_COMMIT_SHA=${{github.sha}}
        -D MC_BUILD_NUMBER=${{github.run_number}}
        -D CPACK_GENERATOR=DEB
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        path: |
          ${{github.workspace}}/build/midiconn
          ${{github.workspace}}/build/*.deb
